services:
  leafy-transport.api:
    image: leafy-transport.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CONNECTIONSTRINGS__PGCONNECTION: ${CONNECTIONSTRINGS__PGCONNECTION}
      JWT__SECRETKEY: ${JWT__SECRETKEY}
      JWT__ISSUER: ${JWT__ISSUER}
      JWT__AUDIENCE: ${JWT__AUDIENCE}
      JWT__EXPIRATIONINMINUTES: ${JWT__EXPIRATIONINMINUTES}
